Repository hwameistor/hwameistor, pull requests merged in 2023-11, with the labels that each got.

#1214 Temporarily remove adaptation test for version 1.23
  .github/workflows/adaptation-test.yml
Labels: e2e-test

#1215 e2e-test: add clone test
  test/e2e/E2eTest/ls_clone_tests.go
Labels: e2e-test

#1217 fix(LocalStorage): LocalVolumeConvert state transition error
  pkg/local-storage/member/controller/volume_convert_task_worker.go
Labels: kind/enhancement

#1211 fix: exit when indexer add failed
  cmd/local-disk-manager/diskmanager.go
Labels: kind/bug

#1223 Upgrade the k8s version for adaptation test
  .github/workflows/adaptation-test.yml
Labels: e2e-test

#1229 fix(migrate): use storage node ip when migrate volume
  pkg/local-storage/member/controller/volume_migrate_task_worker.go
Labels: kind/enhancement

#1226 add drbd parse event test example
  pkg/local-storage/member/node/configer/drbd_test.go
Labels: kind/unit-test

#1231 fix(data-copy): prune replica after unpublish
  pkg/local-storage/member/controller/volume_migrate_task_worker.go
  pkg/local-storage/member/node/datacopy_volume_mount_worker.go
  pkg/local-storage/utils/datacopy/syncer.go
Labels: kind/bug

#1233 fix snapshot doc
  docs/docs/quick_start/advanced_features/volume_snapshot.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/volume_snapshot.md
Labels: kind/documentation

#1235 fix bug missing pvc in cache map
  pkg/local-storage/member/controller/scheduler/resources.go
Labels: kind/bug

#1238 fix(local-storage): potential data race in registry
  pkg/local-storage/member/node/storage/registry.go
Labels: kind/bug

#1245 feat(snapshot): delay volume deletion when snapshots found
  pkg/local-storage/member/csi/controller.go
  pkg/local-storage/member/node/volume_replica_task_worker.go
  pkg/scheduler/scheduler/scheduler-lvm.go
Labels: kind/enhancement

#1239 Migrate
  pkg/apis/hwameistor/v1alpha1/localvolumemigrate_types.go
  pkg/local-storage/member/controller/volume_migrate_task_worker.go
  pkg/scheduler/scheduler/scheduler-lvm.go
Labels: kind/bug

#1248 make indexer for snapshots
  cmd/local-storage/storage.go
Labels: kind/bug

#1246 fixed the migrate prune
  pkg/local-storage/member/controller/volume_migrate_task_worker.go
  pkg/local-storage/member/node/datacopy_volume_mount_worker.go
  pkg/local-storage/utils/datacopy/manager.go
  pkg/local-storage/utils/datacopy/syncer.go
Labels: kind/bug

#1234 add snapshot,expand api
  pkg/apis/hwameistor/v1alpha1/types.go
  pkg/apiserver/api/metric.go
  pkg/apiserver/api/model.go
  pkg/apiserver/api/snapshot.go
  pkg/apiserver/api/volume.go
  pkg/apiserver/controller/MetricsController.go
  pkg/apiserver/controller/SnapshotController.go
  pkg/apiserver/controller/VolumeController.go
  pkg/apiserver/docs/docs.go
  pkg/apiserver/docs/swagger.json
  pkg/apiserver/docs/swagger.yaml
  pkg/apiserver/manager/hwameistor/localsnapshot_controller.go
  pkg/apiserver/manager/hwameistor/localvolume_controller.go
  pkg/apiserver/manager/hwameistor/metric_controller.go
  pkg/apiserver/manager/manager.go
  pkg/apiserver/router/router.go
  pkg/apiserver/util/utils.go
Labels: kind/feature

#1253 fix typos
  README.md
Labels: kind/documentation

#1249 add more events for localdiskclaim
  pkg/apis/hwameistor/v1alpha1/types.go
  pkg/local-disk-manager/controller/localdiskclaim/localdiskclaim_controller.go
  pkg/local-disk-manager/filter/filter_disk.go
  pkg/local-disk-manager/handler/localdisk/localdisk.go
  pkg/local-disk-manager/handler/localdiskclaim/localdiskclaim.go
  pkg/local-storage/member/node/local_disk_claim_task_worker.go
Labels: kind/enhancement

#1259 [zh] Add contribute folder
  docs/i18n/cn/docusaurus-plugin-content-docs/current/contribute/CONTRIBUTING.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/contribute/_category_.json
  docs/i18n/cn/docusaurus-plugin-content-docs/current/contribute/members.yaml
  docs/i18n/cn/docusaurus-plugin-content-docs/current/contribute/membership.md
Labels: kind/documentation

#1260 improve(diskclaim): only record disk claim events when disk is Available
  pkg/local-disk-manager/filter/filter_disk.go
  pkg/local-disk-manager/handler/localdisk/localdisk.go
  pkg/local-disk-manager/handler/localdiskclaim/localdiskclaim.go
Labels: kind/enhancement

#1262 Fix nav and toc issues
  docs/docs/apps/_category_.json
  docs/docs/apps/ha.md
  docs/docs/apps/lvm.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current.json
  docs/i18n/cn/docusaurus-plugin-content-docs/current/apps/_category_.json
  docs/i18n/cn/docusaurus-plugin-content-docs/current/apps/disk.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/apps/ha.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/apps/lvm.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/install/operator.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes/volume_provisioned_io.md
Labels: kind/documentation

#1264 [en] Add website preview instructions to README
  README.md
Labels: kind/documentation

#1263 Release v0.13.1
  CHANGELOG.md
  changelogs/released/v0.13.1/changelog
  helm/hwameistor/Chart.yaml
Labels: release

#1265 Update readme_zh.md
  README.md
  README_zh.md
  docs/docs/img/cncf-cloud-gophers-transparent.png
Labels: kind/documentation

#1261 improve(apiserver): add owner check for SetStorageNodeDiskOwner api
  pkg/apiserver/controller/NodeController.go
  pkg/apiserver/manager/hwameistor/localstoragenode_controller.go
  pkg/local-disk-manager/handler/localdisk/localdisk.go
Labels: kind/enhancement

#1270 fix(apiserver): add exit system statement when indexer setup failed
  pkg/apiserver/router/router.go
Labels: kind/bug

#1268 improve(apiserver):move ldHandler for improving cohesion
  pkg/apiserver/controller/NodeController.go
  pkg/apiserver/manager/hwameistor/localstoragenode_controller.go
  pkg/apiserver/manager/manager.go
  pkg/apiserver/router/router.go
  pkg/hwameictl/cmdparser/disk/disk_reserve.go
Labels: kind/enhancement

#1279 update volumeclone
  README.md
  README_zh.md
Labels: kind/documentation

#1281 [unit-test] add updateLocalVolumeGroupAccessibility test
  pkg/local-storage/member/controller/volumegroup/manager_test.go
Labels: kind/unit-test

#1274 fix(apiserver): getAvailableDiskCapacity found an empty capacity
  pkg/apiserver/manager/hwameistor/localstoragenode_controller.go
Labels: kind/bug

#1275 fix(apiserver): fix StorageNodePoolDiskGet get localdisk from a wrong path
  pkg/apiserver/manager/hwameistor/localstoragenode_controller.go
Labels: kind/bug

#1286 update FAQ
  docs/docs/faqs.md
Labels: kind/documentation

#1289 update migrate e2e
  test/e2e/E2eTest/ls_haVolume_Migrate_tests.go
Labels: e2e-test

#1284 fix(volume-group): always keep accessibility consistent with all volumes in group
  pkg/local-storage/member/controller/volumegroup/manager.go
Labels: kind/bug

#1290 fix bug pending when pruning replica for localvolumemigrate
  pkg/local-storage/member/controller/volume_migrate_task_worker.go
Labels: kind/bug
