Repository hwameistor/hwameistor, pull requests merged in 2023-12, with the labels that each got.

#1292 change client type for supporting fake client to test
  pkg/local-disk-manager/builder/localdisknode/Kubernetes.go
  pkg/local-disk-manager/builder/localdiskvolume/Kubernetes.go
Labels: kind/enhancement

#1291 fix(volume-group): fix node accessability incorrect caused by point reference
  pkg/local-storage/member/controller/volumegroup/manager.go
Labels: kind/bug

#1297 [unit-test] add localdiskclaim worker test
  pkg/local-disk-manager/member/node/localdiskclaim_task_worker_test.go
Labels: kind/unit-test

#1296 [unit-test]add volume internal test
  pkg/local-disk-manager/member/controller/volume/internal_test.go
Labels: kind/unit-test

#1288 [unit-test]add smartctl command result example
  pkg/local-disk-manager/smart/smart_collect_test.go
Labels: kind/unit-test

#1304 improve(apiserver): improve node-controller query efficiency
  pkg/apiserver/controller/NodeController.go
  pkg/apiserver/manager/hwameistor/localstoragenode_controller.go
Labels: kind/enhancement

#1303 [unit-test] add more test for disk internal
  pkg/local-disk-manager/member/controller/disk/internal_test.go
Labels: kind/unit-test

#1308 fix pool disk show bug
  pkg/apiserver/api/node.go
  pkg/apiserver/manager/hwameistor/localstoragenode_controller.go
  pkg/apiserver/manager/hwameistor/localstoragepool_controller.go
Labels: kind/bug

#1318 remove meaningless poolType using
  pkg/local-storage/member/controller/scheduler/resources.go
  pkg/local-storage/member/csi/controller.go
  pkg/local-storage/member/csi/parser.go
  pkg/local-storage/member/node/local_disk_claim_task_worker.go
  pkg/local-storage/utils/utils.go
  pkg/local-storage/utils/utils_test.go
  pkg/scheduler/scheduler/scheduler-lvm.go
Labels: kind/cleanup

#1316 fix(csi-volume): fix volume leaks when user delete pvc but pv not created
  pkg/local-storage/member/csi/controller.go
Labels: kind/bug, kind/enhancement

#1321 improve(apiserver):check LocalDisks length when ListLocalDiskByNodeDevicePath returns
  pkg/apiserver/manager/hwameistor/localstoragenode_controller.go
Labels: kind/enhancement

#1317 Use simplified sc for testing
  test/e2e/E2eTest/ls_Volume_Migrate_tests.go
  test/e2e/E2eTest/ls_clone_tests.go
  test/e2e/E2eTest/ls_comprehensive_tests.go
  test/e2e/E2eTest/ls_convert_tests.go
  test/e2e/E2eTest/ls_eviction_tests.go
  test/e2e/E2eTest/ls_haVolume_Migrate_extra_tests.go
  test/e2e/E2eTest/ls_haVolume_Migrate_tests.go
  test/e2e/E2eTest/ls_haVolume_tests.go
  test/e2e/E2eTest/ls_iop_tests.go
  test/e2e/E2eTest/ls_nodeMount_tests.go
  test/e2e/E2eTest/ls_reliability_tests.go
  test/e2e/E2eTest/ls_scheduler_tests.go
  test/e2e/E2eTest/ls_throughput_tests.go
  test/e2e/E2eTest/ls_volume_expand_tests.go
  test/e2e/E2eTest/ls_volume_tests.go
  test/e2e/E2eTest/performance_tests.go
  test/e2e/E2eTest/pr_tests.go
  test/e2e/E2eTest/pvc_autoresizer_tests.go
  test/e2e/E2eTest/snapshot_restore_tests.go
  test/e2e/E2eTest/snapshot_rollback_tests.go
  test/e2e/E2eTest/stress_bulkDelete_tests.go
  test/e2e/E2eTest/stress_deduplication_tests.go
Labels: kind/enhancement, e2e-test

#1325 add VolumeSnapshotClass
  pkg/apiserver/api/snapshotclass.go
  pkg/apiserver/manager/hwameistor/snapshotclass_controller.go
  pkg/hwameictl/cmdparser/hwameictl.go
  pkg/hwameictl/cmdparser/snapshotclass/snapshotclass_add.go
  pkg/hwameictl/cmdparser/snapshotclass/snapshotclass_delete.go
  pkg/hwameictl/cmdparser/snapshotclass/snapshotclass_list.go
  pkg/hwameictl/cmdparser/snapshotclass/storageclass.go
  pkg/hwameictl/manager/kubeconfig.go
  pkg/hwameictl/manager/manager.go
Labels: kind/feature

#1298 fix volume expand bug
  pkg/apiserver/manager/hwameistor/localvolume_controller.go
Labels: kind/bug

#1309 add ctl storageclass api
  pkg/apiserver/api/storageclass.go
  pkg/apiserver/manager/hwameistor/storageclass_controller.go
  pkg/apiserver/manager/manager.go
  pkg/hwameictl/cmdparser/hwameictl.go
  pkg/hwameictl/cmdparser/snapshotclass/snapshotclass_add.go
  pkg/hwameictl/cmdparser/storageclass/storageclass_add.go
  pkg/hwameictl/cmdparser/storageclass/storageclass_delete.go
  pkg/hwameictl/cmdparser/storageclass/storageclass_list.go
  pkg/hwameictl/cmdparser/storageclass/stroageclass.go
  pkg/hwameictl/manager/manager.go
Labels: kind/feature

#1332 fix bullets consistency in faq page
  docs/docs/faqs.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/faqs.md
Labels: kind/documentation

#1335 Release v0.14.0
  CHANGELOG.md
  changelogs/released/v0.14.0/changelog
  helm/hwameistor/Chart.yaml
  helm/hwameistor/values.yaml
Labels: release
