Repository hwameistor/hwameistor, pull requests merged in 2023-08, with the labels that each got.

#1034 update pr test paths
  .github/workflows/pr.yml
Labels: e2e-test

#1021 update uninstall commands
  docs/docs/quick_start/uninstall.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/uninstall.md
Labels: kind/documentation

#1032 add more attributes to localdisk
  deploy/crds/hwameistor.io_localdisks_crd.yaml
  pkg/apis/hwameistor/v1alpha1/localdisk_types.go
  pkg/apis/hwameistor/v1alpha1/zz_generated.deepcopy.go
  pkg/local-disk-manager/builder/localdisk/localdisk.go
  pkg/local-disk-manager/disk/manager/attribute.go
  pkg/local-disk-manager/localdisk/localdisk.go
  pkg/local-disk-manager/lsblk/attribute.go
  pkg/local-disk-manager/udev/device.go
Labels: kind/feature

#1033 feat(local-storage): support ext{x} filesystem
  build/local-storage/Dockerfile
Labels: kind/bug, kind/feature

#1036 Add membership.md and members.yaml
  README.md
  docs/docs/contribute/CONTRIBUTING.md
  docs/docs/contribute/_category_.json
  docs/docs/contribute/members.yaml
  docs/docs/contribute/membership.md
Labels: kind/documentation

#1037 Modify pr test coverage
  .github/workflows/pr.yml
Labels: e2e-test

#1043 add lv node check in convert tests
  test/e2e/E2eTest/ls_convert_tests.go
Labels: e2e-test

#1046 add convert tests in periodcheck
  test/e2e/E2eTest/ls_convert_tests.go
Labels: e2e-test

#1048 update output of kubectl get
  docs/docs/quick_start/advanced_features/node_expansion.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/node_expansion.md
Labels: kind/documentation

#1050 update checkout job
  .github/workflows/adaptation-test.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/performance-test.yml
  .github/workflows/period-check.yml
  .github/workflows/pr.yml
  .github/workflows/release-builder.yml
  .github/workflows/release-chart.yaml
  .github/workflows/release-exporter.yml
  .github/workflows/release-image.yaml
  .github/workflows/relok8s-check.yml
  .github/workflows/stress-test.yml
Labels: e2e-test

#1039 Update LocalDisk/LocalDiskVolume to identify Disk/DiskVolume
  deploy/crds/hwameistor.io_localdiskvolumes_crd.yaml
  pkg/apis/hwameistor/v1alpha1/localdisk_types.go
  pkg/apis/hwameistor/v1alpha1/localdiskvolume_types.go
  pkg/apis/hwameistor/v1alpha1/zz_generated.deepcopy.go
  pkg/local-disk-manager/builder/localdiskvolume/localdiskvolume.go
  pkg/local-disk-manager/disk/manager/disk.go
  pkg/local-disk-manager/localdisk/localdisk.go
  pkg/local-disk-manager/udev/device.go
Labels: kind/bug, kind/enhancement, kind/feature

#1055 Fix the output of kubectl get in node expansion
  docs/docs/quick_start/advanced_features/node_expansion.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/node_expansion.md
Labels: kind/documentation

#1057 add field to record device history info
  deploy/crds/hwameistor.io_localdisks_crd.yaml
  pkg/apis/hwameistor/v1alpha1/localdisk_types.go
  pkg/apis/hwameistor/v1alpha1/zz_generated.deepcopy.go
Labels: kind/enhancement, kind/feature

#1061 update e2e test
  .github/workflows/pr.yml
  test/e2e/E2eTest/apiserver_check_tests.go
Labels: e2e-test

#1063 update auditor image in e2e test
  test/e2e-test.sh
  test/pr-test.sh
Labels: e2e-test

#1058 Use Serial/IDPATH to Identify Disk
  cmd/local-disk-manager/diskmanager.go
  deploy/crds/hwameistor.io_localdisks_crd.yaml
  deploy/crds/hwameistor.io_localdiskvolumes_crd.yaml
  docs/docs/quick_start/install/prereq.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/install/prereq.md
  pkg/apis/hwameistor/v1alpha1/localdisk_types.go
  pkg/apis/hwameistor/v1alpha1/localdiskvolume_types.go
  pkg/local-disk-manager/builder/localdiskvolume/localdiskvolume.go
  pkg/local-disk-manager/controller/localdisk/localdisk_controller.go
  pkg/local-disk-manager/controller/localdiskclaim/localdiskclaim_controller_test.go
  pkg/local-disk-manager/controller/localdiskvolume/localdiskvolume_controller.go
  pkg/local-disk-manager/disk/controller.go
  pkg/local-disk-manager/disk/eventhandler.go
  pkg/local-disk-manager/disk/manager/disk.go
  pkg/local-disk-manager/disk/queue.go
  pkg/local-disk-manager/filter/filter_disk.go
  pkg/local-disk-manager/handler/localdisk/localdisk.go
  pkg/local-disk-manager/handler/localdiskclaim/localdiskclaim_test.go
  pkg/local-disk-manager/handler/localdiskvolume/localdiskvolume.go
  pkg/local-disk-manager/localdisk/localdisk.go
  pkg/local-disk-manager/member/controller/disk/internal.go
  pkg/local-disk-manager/member/controller/disk/manager.go
  pkg/local-disk-manager/member/controller/volume/internal.go
  pkg/local-disk-manager/member/node/localdiskclaim_task_worker.go
  pkg/local-disk-manager/member/node/pool/internal.go
  pkg/local-disk-manager/member/node/pool/manager.go
  pkg/local-disk-manager/member/node/registry/internal.go
  pkg/local-disk-manager/member/node/registry/manager.go
  pkg/local-disk-manager/utils/kubernetes/kubernetes.go
Labels: kind/enhancement, kind/feature

#1070 Update documentation related to localdisks
  docs/docs/quick_start/install/post_check.md
  docs/docs/volumes_and_nodes/node_expansion/disk_nodes.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/install/post_check.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes_and_nodes/node_expansion/disk_nodes.md
Labels: kind/documentation

#1074 Release Proposal v0.12.0
  CHANGELOG.md
  changelogs/released/v0.12.0/changelog
  helm/hwameistor/Chart.yaml
Labels: release

#1078 update faqs.md
  docs/docs/faqs.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/faqs.md
Labels: kind/documentation

#1085 add doc for snapshot
  docs/docs/quick_start/advanced_features/volume_snapshot.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/volume_snapshot.md
Labels: kind/documentation

#1093 fix panic err when notfound
  pkg/local-storage/member/node/volume_replica_snapshot_task_worker.go
Labels: kind/bug

#1094 add doc for snapshot roollback
  docs/docs/quick_start/advanced_features/volume_snapshot.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/volume_snapshot.md
Labels: kind/documentation

#1016 add new component pvc-autoresizer
  Makefile
  Makefile.variables
  build/pvc-autoresizer/Dockerfile
  cmd/pvc-autoresizer/main.go
  deploy/crds/hwameistor.io_resizepolicies_crd.yaml
  helm/hwameistor/.relok8s-images.yaml
  helm/hwameistor/templates/_helpers.tpl
  helm/hwameistor/templates/pvc-autoresizer.yaml
  helm/hwameistor/values.yaml
  pkg/apis/hwameistor/v1alpha1/resizepolicy_types.go
  pkg/apis/hwameistor/v1alpha1/zz_generated.deepcopy.go
  pkg/pvc-autoresizer/autoresizer.go
  pkg/pvc-autoresizer/const.go
  pkg/pvc-autoresizer/defaultpolicyhooker.go
Labels: kind/enhancement, kind/feature

#1095 release v0.12.0
  CHANGELOG.md
  changelogs/released/v0.12.0/changelog
  helm/hwameistor/Chart.yaml
  helm/hwameistor/values.yaml
Labels: release

#1096 fix release note
  CHANGELOG.md
  changelogs/released/v0.12.0/changelog
Labels: kind/documentation
