Repository hwameistor/hwameistor, pull requests merged in 2023-10, with the labels that each got.

#1160 feat: parse disk type of NVMe
  pkg/local-disk-manager/utils/sys/devices.go
Labels: kind/enhancement

#1163 chroe: fix golangci-lint
  Makefile
Labels: kind/bug

#1162 chore(disk-filter): add logger for debugging disk claim process
  pkg/local-disk-manager/filter/filter_disk.go
  pkg/local-disk-manager/handler/localdiskclaim/localdiskclaim.go
Labels: kind/enhancement

#1164 add 1.28 Adaptation-test
  .github/workflows/adaptation-test.yml
  test/e2e/ad_rollback.sh
  test/e2e/adaptation_test/ad_k8s128_tests.go
Labels: e2e-test

#1165 fix: correct safelyMount check
  pkg/local-disk-manager/handler/localdiskvolume/localdiskvolume.go
  pkg/local-disk-manager/member/types/pool.go
Labels: kind/bug

#1166 fix ad-test
  test/e2e/ad_rollback.sh
Labels: e2e-test

#1167 fix(scheduler): schedule the published node when ha-volume is published
  pkg/scheduler/scheduler/scheduler-lvm.go
Labels: kind/bug

#1172 add 1.24 ad-test
  .github/workflows/adaptation-test.yml
  pkg/local-storage/member/controller/scheduler/resources.go
  pkg/scheduler/scheduler/scheduler-lvm.go
  test/e2e/ad_rollback.sh
  test/e2e/adaptation_test/ad_k8s124_tests.go
Labels: e2e-test

#1176 Release v0.12.4
  CHANGELOG.md
  changelogs/released/v0.12.4/changelog
  helm/hwameistor/Chart.yaml
Labels: release

#1178 fix(snaprestore): set restore timeout 600s as default
  pkg/local-storage/member/node/storage/executor_dd.go
Labels: kind/enhancement

#1179 Clean up advanced_features
  docs/docs/quick_start/advanced_features/disk_expansion.md
  docs/docs/quick_start/advanced_features/fast_failover.md
  docs/docs/quick_start/advanced_features/system_audit.md
  docs/docs/quick_start/advanced_features/volume_eviction.md
  docs/docs/quick_start/advanced_features/volume_provisioned_io.md
  docs/docs/quick_start/advanced_features/volume_snapshot.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/disk_expansion.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/fast_failover.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/node_expansion.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/system_audit.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/volume_eviction.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/volume_provisioned_io.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/volume_snapshot.md
Labels: kind/documentation

#1183 set member is default log container
  helm/hwameistor/templates/local-storage.yaml
Labels: kind/enhancement

#1186 Release v0.13.0
  CHANGELOG.md
  changelogs/released/v0.13.0/changelog
  helm/hwameistor/Chart.yaml
Labels: release

#1190 Disable k8s1.23.3 related tests
  .github/workflows/adaptation-test.yml
Labels: e2e-test

#1193 fix(snap-restore): filter replicaSnapRestoreName before commit tasks
  pkg/local-storage/member/controller/volume_snapshot_restore_task_worker.go
Labels: kind/bug

#1194 [WIP] Feat(volume-clone): Support VolumeClone
  deploy/crds/hwameistor.io_localvolumesnapshotrestores_crd.yaml
  examples/clone/sts-mysql_local_clone.yaml
  pkg/apis/hwameistor/v1alpha1/localvolumesnapshotrestore_types.go
  pkg/local-storage/member/csi/controller.go
  pkg/local-storage/member/csi/plugin.go
Labels: kind/feature

#1196 optimize datacopy job name generating
  pkg/local-storage/member/controller/volume_migrate_task_worker.go
Labels: kind/bug

#1203 feat(scheduler): filter node according to sourcevolume accessibility
  pkg/scheduler/scheduler/scheduler-lvm.go
  pkg/scheduler/scheduler/scheduler.go
Labels: kind/feature

#1208 Update docs: pvc_autoresizing.md, volume_clone, and volume_provisioned_io
  docs/docs/quick_start/advanced_features/pvc_autoresizing.md
  docs/docs/quick_start/advanced_features/volume_clone.md
  docs/docs/quick_start/advanced_features/volume_provisioned_io.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/pvc_autoresizing.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/volume_clone.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/quick_start/advanced_features/volume_provisioned_io.md
Labels: kind/documentation
