Repository hwameistor/hwameistor, pull requests merged in 2024-08, with the labels that each got.

#1552 add verbs/patch access for clusterrole
  helm/hwameistor/templates/clusterrole.yaml
Labels: kind/bug

#1561 [Test]Modify the image address
  test/e2e/E2eTest/ls_iop_tests.go
  test/e2e/E2eTest/ls_throughput_tests.go
  test/e2e/E2eTest/performance_tests.go
Labels: e2e-test

#1562 update docs arch
  docs/i18n/cn/docusaurus-plugin-content-docs/current/apps/_category_.json
  docs/i18n/cn/docusaurus-plugin-content-docs/current/apps/disk.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/apps/ha.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/apps/lvm.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/nodes_and_disks/node_expansion.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/storageclass/_category_.json
  docs/i18n/cn/docusaurus-plugin-content-docs/current/storageclass/disk_volumes.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/storageclass/lvm_volumes.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes/_category_.json
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes/expand.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes/local.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes/migrate.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes/pvc_autoresizing.md
Labels: kind/documentation

#1556 Fixed the issue that bound PVC was not filtered
  pkg/local-storage/member/controller/scheduler/resources.go
Labels: Full test

#1564 Release v0.14.7
  CHANGELOG.md
  changelogs/released/v0.14.7/changelog
  helm/hwameistor/Chart.yaml
Labels: release
