Repository hwameistor/hwameistor, pull requests merged in 2024-09, with the labels that each got.

#1566 sync en arch
  docs/docs/apps/_category_.json
  docs/docs/nodes_and_disks/node_expansion.md
  docs/docs/storageclass/_category_.json
  docs/docs/storageclass/disk_volumes.md
  docs/docs/storageclass/lvm_volumes.md
  docs/docs/volumes/_category_.json
  docs/i18n/cn/docusaurus-plugin-content-docs/current.json
Labels: kind/documentation

#1567 fix node disk reference not created but mount
  pkg/local-disk-manager/controller/localdiskvolume/localdiskvolume_controller.go
  pkg/local-disk-manager/csi/driver/controller/controller.go
  pkg/local-disk-manager/handler/localdiskvolume/localdiskvolume.go
  pkg/local-disk-manager/member/controller/volume/internal.go
  pkg/local-disk-manager/member/controller/volume/manager.go
Labels: kind/bug, Full test

#1549 update docker build
  build/CentOS-Base.repo
  build/admission/Dockerfile
  build/apiserver/Dockerfile
  build/auditor/Dockerfile
  build/dataset-manager/Dockerfile
  build/evictor/Dockerfile
  build/exporter/Dockerfile
  build/failover-assistant/Dockerfile
  build/local-disk-action-controller/Dockerfile
  build/local-disk-manager/Dockerfile
  build/local-storage/Dockerfile
  build/pvc-autoresizer/Dockerfile
  build/scheduler/Dockerfile
Labels: e2e-test, Full test

#1571 add gosec scan
  .github/workflows/period-check.yml
  .github/workflows/pr.yml
Labels: ci

#1579 docs: correct volume replica description
  docs/docs/apps/ha.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/apps/ha.md
Labels: kind/documentation

#1580 Docs: update roadmap for data encryption
  README.md
  README_zh.md
Labels: kind/documentation
