Repository hwameistor/hwameistor, pull requests merged in 2024-01, with the labels that each got.

#1334 [unit-test]fix run failed volume_migrate_task test
  pkg/local-storage/member/controller/volume_migrate_task_worker_test.go
Labels: kind/unit-test

#1339 improve(apiserver):check localdisk exist before using
  pkg/apiserver/manager/hwameistor/localstoragenode_controller.go
Labels: kind/enhancement

#1347 Added documentation for DRBDs adapted kernel version
  docs/docs/install/prereq.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/install/prereq.md
Labels: kind/documentation

#1348 Beautify document structure
  docs/docs/install/prereq.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/install/prereq.md
Labels: kind/documentation

#1349 Beautify document structure
  docs/docs/install/prereq.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/install/prereq.md
Labels: kind/documentation

#1350 Beautify document structure
  docs/docs/install/prereq.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/install/prereq.md
Labels: kind/documentation

#1365 [docs] update readme
  README.md
  README_zh.md
Labels: kind/documentation

#1367 update snapshot client
  pkg/apis/client/clientset/versioned/typed/hwameistor/v1alpha1/fake/fake_hwameistor_client.go
  pkg/apis/client/clientset/versioned/typed/hwameistor/v1alpha1/fake/fake_localvolumesnapshot.go
  pkg/apis/client/clientset/versioned/typed/hwameistor/v1alpha1/fake/fake_localvolumesnapshotrestore.go
  pkg/apis/client/clientset/versioned/typed/hwameistor/v1alpha1/generated_expansion.go
  pkg/apis/client/clientset/versioned/typed/hwameistor/v1alpha1/hwameistor_client.go
  pkg/apis/client/clientset/versioned/typed/hwameistor/v1alpha1/localvolumesnapshot.go
  pkg/apis/client/clientset/versioned/typed/hwameistor/v1alpha1/localvolumesnapshotrestore.go
  pkg/apis/client/informers/externalversions/generic.go
  pkg/apis/client/informers/externalversions/hwameistor/v1alpha1/interface.go
  pkg/apis/client/informers/externalversions/hwameistor/v1alpha1/localvolumesnapshot.go
  pkg/apis/client/informers/externalversions/hwameistor/v1alpha1/localvolumesnapshotrestore.go
  pkg/apis/client/listers/hwameistor/v1alpha1/expansion_generated.go
  pkg/apis/client/listers/hwameistor/v1alpha1/localvolumesnapshot.go
  pkg/apis/client/listers/hwameistor/v1alpha1/localvolumesnapshotrestore.go
  pkg/apis/hwameistor/v1alpha1/localvolumesnapshot_types.go
  pkg/apis/hwameistor/v1alpha1/localvolumesnapshotrestore_types.go
Labels: kind/enhancement

#1369 add cluster insatll ctl
  pkg/hwameictl/cmdparser/cluster/cluster.go
  pkg/hwameictl/cmdparser/cluster/install.go
  pkg/hwameictl/cmdparser/hwameictl.go
Labels: kind/feature

#1379 skip volume when failurepolicy is ignore
  pkg/webhook/scheduler/mutate.go
Labels: kind/enhancement

#1370 [docs] Update /install/prereq.md
  docs/docs/install/prereq.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/install/prereq.md
Labels: kind/documentation

#1382 release v0.14.1
  CHANGELOG.md
  changelogs/released/v0.14.1/changelog
  helm/hwameistor/Chart.yaml
  helm/hwameistor/values.yaml
Labels: release

#1383 add ctl event cmd
  pkg/hwameictl/cmdparser/cluster/cluster.go
  pkg/hwameictl/cmdparser/cluster/event.go
  pkg/hwameictl/manager/manager.go
Labels: kind/feature
