Repository hwameistor/hwameistor, pull requests merged in 2024-10, with the labels that each got.

#1582 Feat(encrypt/block): Support Encrypt Volume with LUKS
  deploy/crds/hwameistor.io_localvolumereplicas_crd.yaml
  deploy/crds/hwameistor.io_localvolumes_crd.yaml
  pkg/apis/hwameistor/v1alpha1/localvolume_types.go
  pkg/apis/hwameistor/v1alpha1/localvolumereplica_types.go
  pkg/apis/hwameistor/v1alpha1/zz_generated.deepcopy.go
  pkg/local-storage/member/csi/controller.go
  pkg/local-storage/member/csi/node.go
  pkg/local-storage/member/csi/parser.go
  pkg/local-storage/member/csi/types.go
  pkg/local-storage/member/node/encrypt/encrypt.go
  pkg/local-storage/member/node/encrypt/luks.go
  pkg/local-storage/member/node/storage/storage.go
  pkg/local-storage/member/node/volume_task_worker.go
Labels: kind/enhancement, kind/feature, Full test

#1583 Feat: Close encrypt volume after unmount volume
  pkg/local-storage/member/csi/mounter.go
  pkg/local-storage/member/csi/node.go
  pkg/local-storage/member/node/encrypt/luks.go
Labels: kind/enhancement, kind/feature, Full test

#1584 rename secureSecret in StorageClass for clarity
  pkg/local-storage/member/csi/parser.go
Labels: kind/enhancement

#1587 update NewLUKS()
  build/local-storage/Dockerfile
  pkg/local-storage/member/node/encrypt/luks.go
Labels: kind/bug

#1590 [Test]add the e2e-test of Volumes Encrypt
  .github/workflows/full-test.yml
  test/e2e/E2eTest/ls_encrypt_tests.go
Labels: e2e-test

#1585 update csi to v4.0.0
  helm/hwameistor/values.yaml
Labels: Full test

#1589 [doc]add the doc of Volumes Encrypt
  docs/docs/volumes/volume_encrypt.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes/volume_encrypt.md
Labels: kind/documentation

#1591 [Docs] update volumes/volume_encrypt.md
  docs/docs/volumes/volume_encrypt.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes/volume_encrypt.md
Labels: kind/documentation

#1593 [doc]add faq for HonorPVReclaimPolicy
  docs/docs/faqs.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/faqs.md
Labels: kind/documentation

#1596 Release v0.16.0
  CHANGELOG.md
  changelogs/released/v0.16.0/changelog
  helm/hwameistor/Chart.yaml
Labels: release

#1598 Docs: Update encrypt as completed
  README.md
  README_zh.md
  docs/docs/volumes/volume_encrypt.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes/volume_encrypt.md
Labels: kind/documentation
