Repository hwameistor/hwameistor, pull requests merged in 2024-06, with the labels that each got.

#1489 Cancel image acceleration in e2e test
  test/e2e/utils/utils.go
Labels: e2e-test

#1494 cleanup dataset manager code
  Makefile
  Makefile.variables
  cmd/dataset-manager/dataset-manager.go
  go.mod
  go.sum
  pkg/dataset-manager/dataset/dataset_worker.go
  pkg/dataset-manager/manager.go
  pkg/dataset-manager/persistentvolume/pv_worker.go
  vendor/github.com/hwameistor/datastore/LICENSE
  vendor/github.com/hwameistor/datastore/pkg/apis/client/clientset/versioned/clientset.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/clientset/versioned/doc.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/clientset/versioned/scheme/doc.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/clientset/versioned/scheme/register.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/clientset/versioned/typed/datastore/v1alpha1/basemodel.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/clientset/versioned/typed/datastore/v1alpha1/checkpoint.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/clientset/versioned/typed/datastore/v1alpha1/dataloadrequest.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/clientset/versioned/typed/datastore/v1alpha1/dataset.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/clientset/versioned/typed/datastore/v1alpha1/datastore_client.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/clientset/versioned/typed/datastore/v1alpha1/doc.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/clientset/versioned/typed/datastore/v1alpha1/generated_expansion.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/informers/externalversions/datastore/interface.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/informers/externalversions/datastore/v1alpha1/basemodel.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/informers/externalversions/datastore/v1alpha1/checkpoint.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/informers/externalversions/datastore/v1alpha1/dataloadrequest.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/informers/externalversions/datastore/v1alpha1/dataset.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/informers/externalversions/datastore/v1alpha1/interface.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/informers/externalversions/factory.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/informers/externalversions/generic.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/listers/datastore/v1alpha1/basemodel.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/listers/datastore/v1alpha1/checkpoint.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/listers/datastore/v1alpha1/dataloadrequest.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/listers/datastore/v1alpha1/dataset.go
  vendor/github.com/hwameistor/datastore/pkg/apis/client/listers/datastore/v1alpha1/expansion_generated.go
  vendor/github.com/hwameistor/datastore/pkg/apis/datastore/v1alpha1/basemodel_types.go
  vendor/github.com/hwameistor/datastore/pkg/apis/datastore/v1alpha1/checkpoint_types.go
  vendor/github.com/hwameistor/datastore/pkg/apis/datastore/v1alpha1/dataloadrequest_types.go
  vendor/github.com/hwameistor/datastore/pkg/apis/datastore/v1alpha1/dataset_types.go
  vendor/github.com/hwameistor/datastore/pkg/apis/datastore/v1alpha1/doc.go
  vendor/github.com/hwameistor/datastore/pkg/apis/datastore/v1alpha1/group.go
  vendor/github.com/hwameistor/datastore/pkg/apis/datastore/v1alpha1/register.go
  vendor/github.com/hwameistor/datastore/pkg/apis/datastore/v1alpha1/types.go
  vendor/github.com/hwameistor/datastore/pkg/apis/datastore/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: kind/cleanup

#1495 【e2e】Optimize e2e test
  Makefile
  test/e2e/E2eTest/pr_tests.go
  test/e2e/utils/utils.go
Labels: e2e-test

#1497 Release v0.14.5
  CHANGELOG.md
  changelogs/released/v0.14.5/changelog
  helm/hwameistor/Chart.yaml
Labels: release

#1499 fix CVE-2024-24790
  build/builder/Dockerfile
Labels: kind/bug

#1502 [e2e] upgrade $path in e2e test
  test/e2e-test.sh
  test/pr-test.sh
Labels: e2e-test

#1500 add datastore md
  docs/docs/apps/ha.md
  docs/docs/img/datastore.png
  docs/docs/modules/dlm.md
  docs/docs/modules/dsm.md
  docs/docs/volumes/cache.md
  docs/docs/volumes/migrate.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/apps/ha.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/img/datastore.png
  docs/i18n/cn/docusaurus-plugin-content-docs/current/modules/dlm.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/modules/dsm.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes/cache.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes/migrate.md
Labels: kind/documentation

#1504 upgrade e2e test
  test/e2e-test.sh
  test/e2e/utils/utils.go
  test/pr-test.sh
Labels: e2e-test

#1505 remove dataset in helm
  helm/hwameistor/templates/_helpers.tpl
  helm/hwameistor/templates/dataset-manager.yaml
  helm/hwameistor/values.yaml
Labels: kind/cleanup

#1506 docs: update serial check command
  docs/docs/faqs.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/faqs.md
Labels: kind/documentation

#1509 [e2e]open k8s.129 ad test
  .github/workflows/adaptation-test.yml
  test/e2e/adaptation_test/ad_k8s129_tests.go
Labels: e2e-test

#1512 docs: update readme
  README.md
  README_zh.md
Labels: kind/documentation

#1513 Complete cache volume docs
  docs/docs/volumes/cache.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes/cache.md
Labels: kind/documentation

#1514 [Docs] update volumes/cache.md
  docs/docs/volumes/cache.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes/cache.md
Labels: kind/documentation
