Repository hwameistor/hwameistor, pull requests merged in 2024-04, with the labels that each got.

#1432 Release v0.14.2
  CHANGELOG.md
  changelogs/released/v0.14.2/changelog
  helm/hwameistor/Chart.yaml
Labels: release

#1435 make scheduler filter message readable
  pkg/local-disk-manager/scheduler/schduler.go
  pkg/local-storage/member/csi/controller.go
  pkg/scheduler/scheduler/plugins.go
  pkg/scheduler/scheduler/scheduler-lvm.go
  pkg/scheduler/scheduler/scheduler.go
Labels: kind/documentation

#1434 Configure ls default parameters
  cmd/local-storage/storage.go
  helm/hwameistor/templates/local-storage.yaml
  helm/hwameistor/values.yaml
Labels: kind/enhancement

#1440 chore(logger): setup logger after flag parse
  cmd/admission/admission.go
Labels: kind/documentation

#1439 acquire leader lease before serving
  cmd/admission/admission.go
  cmd/admission/app/mutate.go
  go.mod
  helm/hwameistor/templates/admission-controller.yaml
Labels: kind/bug

#1444 【e2e-test】update e2e for auto create secret
  test/e2e/utils/utils.go
Labels: e2e-test

#1445 【e2e-test】update e2e-test to fix admission ca
  test/e2e/hwameistor-admission-ca.yaml
  test/e2e/utils/utils.go
Labels: e2e-test

#1443 refactor(admission): use tls cert from secrets
  cmd/admission/admission.go
  cmd/admission/app/mutate.go
  helm/hwameistor/templates/admission-controller.yaml
  pkg/webhook/config/config.go
Labels: kind/enhancement

#1426 Solve the problem of lvr not sensing pod affinity
  pkg/local-storage/member/controller/scheduler/scheduler.go
  pkg/local-storage/member/controller/volume_migrate_task_worker.go
  pkg/scheduler/scheduler/scheduler.go
Labels: kind/bug

#1454 update e2e ha volume test
  test/e2e/E2eTest/ls_haVolume_tests.go
Labels: e2e-test

#1458 Release v0.14.3
  CHANGELOG.md
  changelogs/released/v0.14.3/changelog
  helm/hwameistor/Chart.yaml
  helm/hwameistor/values.yaml
Labels: release
