Repository hwameistor/hwameistor, pull requests merged in 2024-05, with the labels that each got.

#1462 Docs(FAQ): add docs for expanding storage pool manually
  docs/docs/faqs.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/faqs.md
Labels: kind/documentation

#1461 [Docs] Fix indentations and add code symbols after backticks
  docs/docs/install/operator.md
  docs/docs/use_cases/minio/minio.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/install/operator.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/use_cases/minio/minio.md
Labels: kind/documentation

#1441 fix serial has space character
  pkg/local-disk-manager/member/node/pool/internal.go
Labels: kind/bug

#1471 [e2e] add 1.29 & 1.30 ad-test
  .github/workflows/adaptation-test.yml
  test/e2e/ad_rollback.sh
  test/e2e/adaptation_test/ad_k8s129_tests.go
  test/e2e/adaptation_test/ad_k8s130_tests.go
Labels: e2e-test

#1469 fix concurrent map read and map write
  pkg/local-storage/member/controller/volumegroup/manager.go
Labels: kind/bug

#1482 ApiServer: Modify migration fields and add event sorting
  pkg/apiserver/api/volume.go
  pkg/apiserver/controller/MetricsController.go
  pkg/apiserver/controller/VolumeController.go
  pkg/apiserver/docs/docs.go
  pkg/apiserver/docs/swagger.json
  pkg/apiserver/docs/swagger.yaml
  pkg/apiserver/manager/hwameistor/localvolume_controller.go
  pkg/apiserver/manager/hwameistor/metric_controller.go
  pkg/apiserver/util/utils.go
  pkg/hwameictl/cmdparser/volume/volume_migrate.go
  pkg/hwameictl/cmdparser/volume/volume_migrate_abort.go
Labels: kind/enhancement

#1484 release v0.14.4
  CHANGELOG.md
  changelogs/released/v0.14.4/changelog
  helm/hwameistor/Chart.yaml
  helm/hwameistor/values.yaml
Labels: release

#1486 fix(CI): bump go version to 1.20.5 in module and builder
  build/Dockerfile
  build/builder/Dockerfile
  go.mod
Labels: kind/bug
