Repository hwameistor/hwameistor, pull requests merged in 2024-07, with the labels that each got.

#1518 [image-build]update yum repo
  build/admission/Dockerfile
  build/apiserver/Dockerfile
  build/auditor/Dockerfile
  build/dataset-manager/Dockerfile
  build/evictor/Dockerfile
  build/exporter/Dockerfile
  build/failover-assistant/Dockerfile
  build/local-disk-action-controller/Dockerfile
  build/local-disk-manager/Dockerfile
  build/local-storage/Dockerfile
  build/pvc-autoresizer/Dockerfile
  build/scheduler/Dockerfile
Labels: kind/enhancement

#1522 enhance(admission): improve processing static volume
  pkg/webhook/scheduler/mutate.go
Labels: kind/enhancement

#1524 fix(disk-manager): filter out disk with partition table
  pkg/local-disk-manager/lsblk/partition.go
Labels: kind/bug

#1525 [test]add static volume e2e test
  test/e2e/E2eTest/static_volume_tests.go
  test/e2e/utils/utils.go
Labels: e2e-test

#1528 [test]upgrade api test
  test/e2e/API_Performance_Test/api_performance_tests.go
  test/e2e/API_Performance_Test/convert.py
  test/e2e/API_Performance_Test/upload_report.sh
Labels: e2e-test

#1531 [doc]update the drbd support list
  docs/docs/install/prereq.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/install/prereq.md
Labels: kind/documentation

#1519 Change Default ReclaimPolicy from Delete to Retain
  helm/hwameistor/values.yaml
Labels: kind/enhancement

#1539 feat(docs): add search for docs
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
Labels: kind/feature

#1542 [Docs] fix typos and bullet indentations
  docs/docs/faqs.md
  docs/docs/use_cases/tidb.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/faqs.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/use_cases/tidb.md
Labels: kind/documentation

#1540 fix(scheduler): correct skip policy for affinity and taints
  pkg/local-storage/member/controller/scheduler/scheduler.go
  pkg/local-storage/member/controller/scheduler/scheduler_test.go
Labels: kind/bug, kind/enhancement

#1537 limit RBAC hwameistor-role permissions
  helm/hwameistor/templates/clusterrole.yaml
Labels: kind/bug, Full test

#1543 Release v0.14.6
  CHANGELOG.md
  changelogs/released/v0.14.6/changelog
  helm/hwameistor/Chart.yaml
Labels: release

#1544 build: update yum repo
  build/CentOS-Base.repo
  build/admission/Dockerfile
  build/apiserver/Dockerfile
  build/auditor/Dockerfile
  build/dataset-manager/Dockerfile
  build/evictor/Dockerfile
  build/exporter/Dockerfile
  build/failover-assistant/Dockerfile
  build/local-disk-action-controller/Dockerfile
  build/local-disk-manager/Dockerfile
  build/local-storage/Dockerfile
  build/pvc-autoresizer/Dockerfile
  build/scheduler/Dockerfile
Labels: kind/enhancement

#1547 update base image
  build/admission/Dockerfile
  build/apiserver/Dockerfile
  build/auditor/Dockerfile
  build/dataset-manager/Dockerfile
  build/evictor/Dockerfile
  build/exporter/Dockerfile
  build/failover-assistant/Dockerfile
  build/local-disk-action-controller/Dockerfile
  build/local-disk-manager/Dockerfile
  build/local-storage/Dockerfile
  build/pvc-autoresizer/Dockerfile
  build/scheduler/Dockerfile
Labels: ci

#1548 docs: update compatibility for 1.29,1.30
  README.md
  README_zh.md
Labels: kind/documentation
