Repository hwameistor/hwameistor, pull requests merged in 2025-03, with the labels that each got.

#1667 Added documentation for Metrics
  docs/docs/faqs.md
  docs/docs/metrics.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/faqs.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/metrics.md
Labels: kind/documentation

#1666 fix: metadata size for pv is configurable now, default is 4MB
  cmd/local-storage/storage.go
  pkg/apis/hwameistor/local_storage_member.go
  pkg/local-storage/controller/localvolume/localvolume_controller_test.go
  pkg/local-storage/controller/localvolumereplica/localvolumereplica_controller_test.go
  pkg/local-storage/member/member.go
  pkg/local-storage/member/node/local_disk_task_worker.go
  pkg/local-storage/member/node/manager.go
Labels: kind/bug

#1686 [Test]add KubeLinter Test
  .github/workflows/kubelinter-test.yml
  Makefile
  test/kubelinter-test.sh
Labels: e2e-test

#1688 update KubeLinter Test
  test/kubelinter-test.sh
Labels: e2e-test

#1693 Update faqs.md
  docs/docs/faqs.md
Labels: kind/documentation

#1665 Fixed the issue with UI displaying dbrd installation
  pkg/apiserver/manager/hwameistor/setting_controller.go
Labels: kind/bug

#1662 Add node permissions to hwameistor-role so that storage nodes can be …
  helm/hwameistor/templates/clusterrole.yaml
Labels: kind/bug
