Repository hwameistor/hwameistor, pull requests merged in 2025-08, with the labels that each got.

#1738 release v1.0.1-rc2
  helm/hwameistor/Chart.yaml
Labels: release

#1732 feat: thin provisioning for hwameistor
  deploy/crds/hwameistor.io_localdisknodes_crd.yaml
  deploy/crds/hwameistor.io_localstoragenodes_crd.yaml
  deploy/crds/hwameistor.io_localvolumereplicas_crd.yaml
  deploy/crds/hwameistor.io_localvolumereplicasnapshots_crd.yaml
  deploy/crds/hwameistor.io_localvolumes_crd.yaml
  deploy/crds/hwameistor.io_localvolumesnapshots_crd.yaml
  deploy/crds/hwameistor.io_thinpoolclaims_crd.yaml
  docs/docs/volumes/volume_thin.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/volumes/volume_thin.md
  pkg/apis/hwameistor/v1alpha1/localstoragenode_types.go
  pkg/apis/hwameistor/v1alpha1/localvolume_types.go
  pkg/apis/hwameistor/v1alpha1/localvolumereplica_types.go
  pkg/apis/hwameistor/v1alpha1/localvolumereplicasnapshot_types.go
  pkg/apis/hwameistor/v1alpha1/localvolumesnapshot_types.go
  pkg/apis/hwameistor/v1alpha1/thinpoolclaim_types.go
  pkg/apis/hwameistor/v1alpha1/types.go
  pkg/apis/hwameistor/v1alpha1/zz_generated.deepcopy.go
  pkg/exechelper/basicexecutor/executor.go
  pkg/local-disk-manager/controller/add_thinpoolclaim.go
  pkg/local-storage/controller/thinpoolclaim/thinpoolclaim_controller.go
  pkg/local-storage/controller/thinpoolclaim/thinpoolclaim_controller_test.go
  pkg/local-storage/member/controller/manager.go
  pkg/local-storage/member/controller/scheduler/resources.go
  pkg/local-storage/member/controller/scheduler/resources_test.go
  pkg/local-storage/member/controller/scheduler/types.go
  pkg/local-storage/member/controller/volume_expand_task_worker.go
  pkg/local-storage/member/controller/volume_snapshot_restore_task_worker.go
  pkg/local-storage/member/controller/volume_task_worker.go
  pkg/local-storage/member/controller/volumegroup/manager.go
  pkg/local-storage/member/csi/controller.go
  pkg/local-storage/member/csi/mounter.go
  pkg/local-storage/member/csi/mounter_mock.go
  pkg/local-storage/member/csi/node.go
  pkg/local-storage/member/csi/parser.go
  pkg/local-storage/member/csi/types.go
  pkg/local-storage/member/csi/utils.go
  pkg/local-storage/member/node/local_disk_claim_task_worker.go
  pkg/local-storage/member/node/local_disk_claim_task_worker_test.go
  pkg/local-storage/member/node/manager.go
  pkg/local-storage/member/node/storage/executor_lvm.go
  pkg/local-storage/member/node/storage/executor_lvm_test.go
  pkg/local-storage/member/node/storage/pools.go
  pkg/local-storage/member/node/storage/pools_test.go
  pkg/local-storage/member/node/storage/registry.go
  pkg/local-storage/member/node/storage/snapshot.go
  pkg/local-storage/member/node/storage/storage.go
  pkg/local-storage/member/node/storage/types.go
  pkg/local-storage/member/node/storage/validator.go
  pkg/local-storage/member/node/thin_pool_claim_task_worker.go
  pkg/local-storage/member/node/volume_replica_snapshot_task_worker.go
  pkg/local-storage/member/node/volume_replica_task_worker.go
  pkg/local-storage/member/node/volume_task_worker.go
  pkg/local-storage/member/node/volume_task_worker_test.go
  pkg/local-storage/utils/utils.go
  pkg/local-storage/utils/utils_test.go
  pkg/scheduler/scheduler/scheduler-lvm.go
  pkg/scheduler/scheduler/scheduler.go
Labels: kind/feature

#1739 fix Mounter interface error
  pkg/local-storage/member/csi/mounter.go
Labels: kind/bug

#1743 Disable some error testing
  test/e2e/E2eTest/snapshot_rollback_tests.go
  test/e2e/E2eTest/update_tests.go
Labels: e2e-test
