Repository hwameistor/hwameistor, pull requests merged in 2025-06, with the labels that each got.

#1711 feat: schedule optimization
  deploy/crds/hwameistor.io_localstoragenodes_crd.yaml
  deploy/crds/hwameistor.io_localvolumereplicas_crd.yaml
  deploy/crds/hwameistor.io_localvolumereplicasnapshots_crd.yaml
  deploy/crds/hwameistor.io_thinpoolclaims_crd.yaml
  pkg/apis/hwameistor/v1alpha1/localvolumereplica_types.go
  pkg/apis/hwameistor/v1alpha1/localvolumereplicasnapshot_types.go
  pkg/apis/hwameistor/v1alpha1/thinpoolclaim_types.go
  pkg/apis/hwameistor/v1alpha1/types.go
  pkg/apis/hwameistor/v1alpha1/zz_generated.deepcopy.go
  pkg/exechelper/basicexecutor/executor.go
  pkg/local-storage/member/controller/scheduler/resources.go
  pkg/local-storage/member/controller/scheduler/resources_test.go
  pkg/local-storage/member/controller/volume_expand_task_worker.go
  pkg/local-storage/member/csi/controller.go
  pkg/local-storage/member/csi/utils.go
  pkg/local-storage/member/node/storage/executor_lvm.go
  pkg/local-storage/member/node/storage/snapshot.go
  pkg/local-storage/member/node/storage/types.go
  pkg/local-storage/member/node/storage/validator.go
  pkg/local-storage/member/node/volume_replica_snapshot_task_worker.go
  pkg/local-storage/member/node/volume_replica_task_worker.go
Labels: kind/bug

#1718 fix error not handling for volume metrics
  pkg/local-storage/member/csi/node.go
Labels: kind/bug

#1719 disable sync when fetching metrics
  pkg/local-storage/member/csi/utils.go
Labels: kind/bug

#1721 Release v0.16.3
  CHANGELOG.md
  changelogs/released/v0.16.4/changelog
  helm/hwameistor/Chart.yaml
  helm/hwameistor/values.yaml
Labels: release

#1722 [Docs] Clean up metrics.md
  docs/docs/metrics.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/metrics.md
Labels: kind/documentation
